name: glovo-service build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout-code:
    name: Checkout code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build-with_maven:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean
        run: mvn clean

      - name: Validate
        run: mvn validate

      - name: Compile
        run: mvn compile

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package

      - name: Verify
        run: mvn verify

      - name: Install
        run: mvn install

  authenticate-to-gcp:
    name: Authenticate to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

  set-up-docker-to-region:
    name: Set up Docker to region
    needs: authenticate-to-gcp
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker to region
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: europe-west1-docker.pkg.dev/devrate-dev/dev-rate-service/dev-rate:latest

  deploy-to-GCP-VM:
    name: Deploy to GCP VM
    needs: authenticate-to-gcp
    runs-on: ubuntu-latest

    steps:
      # New step for deploying using GCP
      - name: Deploy to GCP VM
        run: |
          # Authenticate with gcloud
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

